concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}
jobs:
  check-dotnet:
    name: "\u0421heck .NET code"
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - continue-on-error: true
      name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - continue-on-error: true
      name: Run checks
      run: 'dotnet build modules/platforms/dotnet/Apache.Ignite.DotNetCore.sln

        '
  check-ducktape:
    name: Check ducktape on ${{ matrix.cfg.toxenv }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - continue-on-error: true
      name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.cfg.python}}
    - continue-on-error: true
      name: Install tox
      run: 'pip install tox==3.27.1

        '
    - continue-on-error: true
      name: Run tests
      run: 'cd modules/ducktests/tests

        tox -e ${{ matrix.cfg.toxenv }}

        '
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - python: '3.7'
          toxenv: py37
        - python: '3.8'
          toxenv: py38
        - python: '3.8'
          toxenv: codestyle
  check-java:
    name: Check java code on JDK ${{ matrix.java }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - continue-on-error: true
      name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Install prerequisites
      run: 'sudo apt-get update && sudo apt-get install libnuma-dev

        '
    - continue-on-error: true
      if: ${{ matrix.java == '11' }}
      name: Set MAVEN_OPTS
      run: 'echo MAVEN_OPTS=''--illegal-access=permit --add-exports=java.base/jdk.internal.misc=ALL-UNNAMED

        --add-exports=java.base/sun.nio.ch=ALL-UNNAMED

        --add-exports=java.management/com.sun.jmx.mbeanserver=ALL-UNNAMED

        --add-exports=jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED

        --add-exports=java.base/sun.reflect.generics.reflectiveObjects=ALL-UNNAMED

        -Djdk.tls.client.protocols=TLSv1.2'' >> $GITHUB_ENV

        '
    - continue-on-error: true
      name: Run codestyle and licenses checks
      run: './mvnw test-compile -Pall-java,licenses,lgpl,checkstyle,examples,all-scala,scala,check-licenses
        -B -V

        '
    - continue-on-error: true
      if: ${{ matrix.java == '8' }}
      name: Run abandoned tests checks.
      run: './mvnw test -Pcheck-test-suites,all-java,all-scala,scala -B -V

        '
    strategy:
      fail-fast: false
      matrix:
        java:
        - '8'
        - '11'
name: Code Style, Abandoned Tests
on:
  repository_dispatch:
    types: trigger-ga___commit-check.yml
