jobs:
  deploy:
    if: github.repository == 'apache/ignite'
    name: Deploy Apache Ignite
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 8
        server-id: apache.snapshots.https
        server-password: NEXUS_PW
        server-username: NEXUS_USER
    - continue-on-error: true
      env:
        NEXUS_PW: ${{ secrets.NEXUS_PW }}
        NEXUS_USER: ${{ secrets.NEXUS_USER }}
      name: Deploy
      run: ./mvnw deploy -Pcheckstyle,compatibility -DskipTests -Dmaven.javadoc.skip=true
        -B -V
name: Publish Apache Ignite Snapshot to Maven Snapshot Repository
on:
  repository_dispatch:
    types: trigger-ga___publish-snapshot.yml
