concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}
jobs:
  sonarcloud:
    if: github.repository == 'apache/ignite'
    name: Sonar Analysis
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: refs/pull/${{ github.event.number }}/merge
    - continue-on-error: true
      name: Set up JDK11
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-sonar
        path: ~/.sonar/cache
        restore-keys: ${{ runner.os }}-sonar
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-m2

          '
    - continue-on-error: true
      name: Install Libnuma
      run: sudo apt-get update && sudo apt-get install libnuma-dev
    - continue-on-error: true
      name: Build with Maven
      run: "./mvnw clean install -P all-java,lgpl,examples,skip-docs -DskipTests -B\
        \ -V          \n"
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        JAVA_OPTS: -XX:+UseG1GC -XX:InitialHeapSize=2g -XX:MaxHeapSize=6g -XX:+UseStringDeduplication
        MAVEN_OPTS: -XX:+UseG1GC -XX:InitialHeapSize=2g -XX:MaxHeapSize=6g -XX:+UseStringDeduplication
        PULLREQUEST_BASE: ${{ github.base_ref }}
        PULLREQUEST_BRANCH: ${{ github.head_ref }}
        PULLREQUEST_KEY: ${{ github.event.pull_request.number }}
        SONARCLOUD_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        SONAR_OPTS: -XX:+UseG1GC -XX:InitialHeapSize=2g -XX:MaxHeapSize=6g -XX:+UseStringDeduplication
      name: Sonar Analyze Upload
      run: './mvnw org.sonarsource.scanner.maven:sonar-maven-plugin:sonar  -P all-java,lgpl,examples,skip-docs
        -Dsonar.pullrequest.branch=${PULLREQUEST_BRANCH} -Dsonar.pullrequest.base=${PULLREQUEST_BASE}
        -Dsonar.pullrequest.key=${PULLREQUEST_KEY} -Dsonar.pullrequest.github.repository=apache/ignite
        -Dsonar.pullrequest.provider=GitHub  -Dsonar.pullrequest.github.summary_comment=true
        -Dsonar.projectKey=apache_ignite -Dsonar.login=${SONARCLOUD_TOKEN} -B -V

        '
name: Sonar Quality Pull Request Analysis
on:
  repository_dispatch:
    types: trigger-ga___sonar-pr-from-fork.yml
permissions:
  contents: read
